FROM ubuntu:16.04
MAINTAINER Ram Murthy "rammurthy.malisetti@gmail.com"


RUN apt-get update && apt-get install -y vim openssh-server openssh-client && apt-get clean

RUN mkdir /var/run/sshd
RUN echo 'root:screencast' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

RUN mkdir /data/
COPY script.sh /data/
RUN chmod +x /data/*sh

EXPOSE 22
ENTRYPOINT ["/usr/sbin/sshd", "-D"]

